[build-system]
requires = [
    "setuptools",
    "setuptools_scm[toml]>=3.4.1",
    "wheel",
    "Cython",
    "numpy",
    "pkgconfig",
    "scikit-build",
    "cmake",
    "ninja;platform_system != \"Windows\"",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
