[build-system]
requires = [
    "setuptools",
    "setuptools_scm[toml]>=3.4.1",
    "wheel",
    "Cython",
    "numpy",
    "pkgconfig",
    "scikit-build",
    "cmake",
    "ninja;platform_system != \"Windows\"",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.cibuildwheel]
archs = ["native"]
skip = "{cp,pp}27-* {cp,pp}35-* pp*"

build-frontend = "build"

test-command = "pytest {package}/tests -v"
before-test = ""
test-requires = ["pytest"]
test-extras = []

manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel pupil-pthreads-win"
repair-wheel-command = [
    'bash scripts/repair-wheels-windows.sh {dest_dir} {wheel}',
]
