name: tests

on:
  pull_request:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  build_wheels:
    name: "Build ${{ matrix.CIBW_BUILD }} wheels on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        CIBW_BUILD: ["*"]
        exclude:
          - os: ubuntu-latest
            CIBW_BUILD: "*"
        include:
          - os: ubuntu-latest
            CIBW_BUILD: "*manylinux*"
          # Disable musllinux
          # - os: ubuntu-latest
          #   CIBW_BUILD: "*musllinux*"
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build ${{ matrix.CIBW_BUILD }} wheels on ${{ matrix.os }}
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_BUILD: ${{ matrix.CIBW_BUILD }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: distribution
          path: ./wheelhouse/*.whl

  release:
    needs: [build_wheels]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: distribution
          path: dist/
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
